name: CI
# only run on merge into main branch
on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  quspin-tests:
    name: Run QuSpin tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: checking pip 
        run:  python -m ensurepip --upgrade

      - name: Checkout QuSpin-Extensions
        uses: actions/checkout@v4

      - name: Install QuSpin-Extensions
        run: pip install -e .

      - name: Checkout QuSpin
        uses: actions/checkout@v4
        with:
          repository: QuSpin/QuSpin

      - name: Install QuSpin
        run: |
          pip install -e .

      - name: Test QuSpin
        run: |
          pip install pytest
          pytest -x

        
